server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seller_service_db
    username: root
    password: root     
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    
product:
  service:
    url: "http://localhost:8083/product"